<?php
/**
 * MessagesApi
 * PHP version 5
 *
 * @category Class
 * @package  RadioCorp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public RadioCorp API [Development]
 *
 * Public/Private API for accessing RadioCorp recources through custom applications.\\ At the moment only available for the stations 100% NL, SLAM! and SLAM!TV ### Available formats ### Available formats (based on the 'Accept' header):\\ json, array, csv, html, jsonp, php, serialized, xml\\ The API defaults to application/json when no header supplied. ### Contact / License ###
 *
 * OpenAPI spec version: v0.0
 * Contact: beheer@radiocorp.nl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RadioCorp\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use RadioCorp\ApiException;
use RadioCorp\Configuration;
use RadioCorp\HeaderSelector;
use RadioCorp\ObjectSerializer;

/**
 * MessagesApi Class Doc Comment
 *
 * @category Class
 * @package  RadioCorp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MessagesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation messagesConversationGet
     *
     * [INTERNAL] Get the conversation based on a message hash
     *
     * @param  string $hash The hash where you want the conversation for (optional)
     * @param  string $page The page you want to retreive (optional)
     *
     * @throws \RadioCorp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \RadioCorp\Model\MessagesList
     */
    public function messagesConversationGet($hash = null, $page = null)
    {
        list($response) = $this->messagesConversationGetWithHttpInfo($hash, $page);
        return $response;
    }

    /**
     * Operation messagesConversationGetWithHttpInfo
     *
     * [INTERNAL] Get the conversation based on a message hash
     *
     * @param  string $hash The hash where you want the conversation for (optional)
     * @param  string $page The page you want to retreive (optional)
     *
     * @throws \RadioCorp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \RadioCorp\Model\MessagesList, HTTP status code, HTTP response headers (array of strings)
     */
    public function messagesConversationGetWithHttpInfo($hash = null, $page = null)
    {
        $request = $this->messagesConversationGetRequest($hash, $page);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\RadioCorp\Model\MessagesList' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\RadioCorp\Model\MessagesList', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\RadioCorp\Model\MessagesList';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RadioCorp\Model\MessagesList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation messagesConversationGetAsync
     *
     * [INTERNAL] Get the conversation based on a message hash
     *
     * @param  string $hash The hash where you want the conversation for (optional)
     * @param  string $page The page you want to retreive (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function messagesConversationGetAsync($hash = null, $page = null)
    {
        return $this->messagesConversationGetAsyncWithHttpInfo($hash, $page)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation messagesConversationGetAsyncWithHttpInfo
     *
     * [INTERNAL] Get the conversation based on a message hash
     *
     * @param  string $hash The hash where you want the conversation for (optional)
     * @param  string $page The page you want to retreive (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function messagesConversationGetAsyncWithHttpInfo($hash = null, $page = null)
    {
        $returnType = '\RadioCorp\Model\MessagesList';
        $request = $this->messagesConversationGetRequest($hash, $page);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'messagesConversationGet'
     *
     * @param  string $hash The hash where you want the conversation for (optional)
     * @param  string $page The page you want to retreive (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function messagesConversationGetRequest($hash = null, $page = null)
    {

        $resourcePath = '/Messages/Conversation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($hash !== null) {
            $queryParams['hash'] = ObjectSerializer::toQueryValue($hash);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation messagesListGet
     *
     * [INTERNAL] Get the messages for this station based on filters defined down here.
     *
     * @param  int $last_msg The id from or up to which message you want to get, if it&#39;s a positive integer you will get messages newer than the provided id, if you provide a negative integer you will get messages older than the id (optional)
     * @param  int $msgs A comma seperated list of message ids you want to receive, in this case, limit will be ommited (optional)
     * @param  int $limit The maximum of messages to return (optional)
     * @param  \DateTime $sincedate Return messages since this datetime (optional)
     * @param  \DateTime $todate Return messages up to this datetime (optional)
     *
     * @throws \RadioCorp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \RadioCorp\Model\MessagesList
     */
    public function messagesListGet($last_msg = null, $msgs = null, $limit = null, $sincedate = null, $todate = null)
    {
        list($response) = $this->messagesListGetWithHttpInfo($last_msg, $msgs, $limit, $sincedate, $todate);
        return $response;
    }

    /**
     * Operation messagesListGetWithHttpInfo
     *
     * [INTERNAL] Get the messages for this station based on filters defined down here.
     *
     * @param  int $last_msg The id from or up to which message you want to get, if it&#39;s a positive integer you will get messages newer than the provided id, if you provide a negative integer you will get messages older than the id (optional)
     * @param  int $msgs A comma seperated list of message ids you want to receive, in this case, limit will be ommited (optional)
     * @param  int $limit The maximum of messages to return (optional)
     * @param  \DateTime $sincedate Return messages since this datetime (optional)
     * @param  \DateTime $todate Return messages up to this datetime (optional)
     *
     * @throws \RadioCorp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \RadioCorp\Model\MessagesList, HTTP status code, HTTP response headers (array of strings)
     */
    public function messagesListGetWithHttpInfo($last_msg = null, $msgs = null, $limit = null, $sincedate = null, $todate = null)
    {
        $request = $this->messagesListGetRequest($last_msg, $msgs, $limit, $sincedate, $todate);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\RadioCorp\Model\MessagesList' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\RadioCorp\Model\MessagesList', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\RadioCorp\Model\MessagesList';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RadioCorp\Model\MessagesList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation messagesListGetAsync
     *
     * [INTERNAL] Get the messages for this station based on filters defined down here.
     *
     * @param  int $last_msg The id from or up to which message you want to get, if it&#39;s a positive integer you will get messages newer than the provided id, if you provide a negative integer you will get messages older than the id (optional)
     * @param  int $msgs A comma seperated list of message ids you want to receive, in this case, limit will be ommited (optional)
     * @param  int $limit The maximum of messages to return (optional)
     * @param  \DateTime $sincedate Return messages since this datetime (optional)
     * @param  \DateTime $todate Return messages up to this datetime (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function messagesListGetAsync($last_msg = null, $msgs = null, $limit = null, $sincedate = null, $todate = null)
    {
        return $this->messagesListGetAsyncWithHttpInfo($last_msg, $msgs, $limit, $sincedate, $todate)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation messagesListGetAsyncWithHttpInfo
     *
     * [INTERNAL] Get the messages for this station based on filters defined down here.
     *
     * @param  int $last_msg The id from or up to which message you want to get, if it&#39;s a positive integer you will get messages newer than the provided id, if you provide a negative integer you will get messages older than the id (optional)
     * @param  int $msgs A comma seperated list of message ids you want to receive, in this case, limit will be ommited (optional)
     * @param  int $limit The maximum of messages to return (optional)
     * @param  \DateTime $sincedate Return messages since this datetime (optional)
     * @param  \DateTime $todate Return messages up to this datetime (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function messagesListGetAsyncWithHttpInfo($last_msg = null, $msgs = null, $limit = null, $sincedate = null, $todate = null)
    {
        $returnType = '\RadioCorp\Model\MessagesList';
        $request = $this->messagesListGetRequest($last_msg, $msgs, $limit, $sincedate, $todate);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'messagesListGet'
     *
     * @param  int $last_msg The id from or up to which message you want to get, if it&#39;s a positive integer you will get messages newer than the provided id, if you provide a negative integer you will get messages older than the id (optional)
     * @param  int $msgs A comma seperated list of message ids you want to receive, in this case, limit will be ommited (optional)
     * @param  int $limit The maximum of messages to return (optional)
     * @param  \DateTime $sincedate Return messages since this datetime (optional)
     * @param  \DateTime $todate Return messages up to this datetime (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function messagesListGetRequest($last_msg = null, $msgs = null, $limit = null, $sincedate = null, $todate = null)
    {

        $resourcePath = '/Messages/List';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($last_msg !== null) {
            $queryParams['last_msg'] = ObjectSerializer::toQueryValue($last_msg);
        }
        // query params
        if ($msgs !== null) {
            $queryParams['msgs'] = ObjectSerializer::toQueryValue($msgs);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($sincedate !== null) {
            $queryParams['sincedate'] = ObjectSerializer::toQueryValue($sincedate);
        }
        // query params
        if ($todate !== null) {
            $queryParams['todate'] = ObjectSerializer::toQueryValue($todate);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
