<?php
/**
 * EPGApiTest
 * PHP version 5
 *
 * @category Class
 * @package  RadioCorp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public RadioCorp API [Development]
 *
 * Public/Private API for accessing RadioCorp recources through custom applications.\\ At the moment only available for the stations 100% NL, SLAM! and SLAM!TV ### Available formats ### Available formats (based on the 'Accept' header):\\ json, array, csv, html, jsonp, php, serialized, xml\\ The API defaults to application/json when no header supplied. ### Contact / License ###
 *
 * OpenAPI spec version: v0.0
 * Contact: beheer@radiocorp.nl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace RadioCorp;

use \RadioCorp\Configuration;
use \RadioCorp\ApiException;
use \RadioCorp\ObjectSerializer;

/**
 * EPGApiTest Class Doc Comment
 *
 * @category Class
 * @package  RadioCorp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EPGApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for epgCurrentShowGet
     *
     * Get the current on-air show..
     *
     */
    public function testEpgCurrentShowGet()
    {
    }

    /**
     * Test case for epgNextShowGet
     *
     * Get the next show which is gonna be aired..
     *
     */
    public function testEpgNextShowGet()
    {
    }

    /**
     * Test case for epgWeeklyEpgGet
     *
     * Get the full Program Guide..
     *
     */
    public function testEpgWeeklyEpgGet()
    {
    }
}
